### ISSUE TITLE
Issue with creation of the chain.hhm file

### ISSUE THREAD

**Issue by Ravy-LFL** [YYingXia/LigBind#1]
Hi,

I am struggling with the creation of the chain.hhm file. Every path was updated and hhblits is install. Do you have an idea about how could i fix it ? Here's the complete error : 

PATH/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 9457.
  warnings.warn(
PATH/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain P is discontinuous at line 9470.
  warnings.warn(
PARH/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 9494.
  warnings.warn(
1. data process...
- 18:27:00.804 INFO: Search results will be written to output/example/chain.hhr

- 18:27:00.804 ERROR: In /PATH/ffindexdatabase.cpp:11: FFindexDatabase:

- 18:27:00.804 ERROR: 	could not open file '/PATH/LigBind/uniclust30_2018_08/_cs219.ffdata'

Traceback (most recent call last):
  File "/PATH/LigBind/prediction.py", line 445, in <module>
    hhm_fea = cal_HMM(query_path, sequence)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PATH/LigBind/prediction.py", line 70, in cal_HMM
    with open('{}/chain.hhm'.format(query_path), 'r') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/example/chain.hhm'

**Comment by YYingXia** [comment]
Hi,

It seems that the database uniclust30_2018_08  is not existed. 
Have you downloaded uniclust30_2018_08 for HHblits and modified the absolute paths of uniclust30_2018_08 databases in the script "./prediction.py"? 
Uniclust30_2018_08 can be download from https://wwwuser.gwdg.de/~compbiol/uniclust/2018_08/.

Hope it helps!

**Comment by Ravy-LFL** [comment]
Thank you it is better now for this point !
